name = "LoggingFacilities"
uuid = "c06cd2c6-3608-4160-890b-5288dd687afb"
authors = ["Amgalanbaatar Baatarjav <amgalan_amg@yahoo.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
